Vishnbd patch 2 (#19)
* Update blackduck.yml and oss-artifactory.yml

diff --git a/.github/workflows/blackduck.yml b/.github/workflows/blackduck.yml
--- a/.github/workflows/blackduck.yml
+++ b/.github/workflows/blackduck.yml
@@ -7,6 +7,7 @@ on:
 
 jobs:
   blackduck-scan:
+    permissions: write-all
     name: Run Black Duck SCA Scan
     runs-on: ubuntu-latest
 
@@ -17,9 +18,10 @@ jobs:
 
       # Check Python version
       - name: Check Python version
-        run: python3 -V
+        run: |
+          python3 -V
 
-      # Run pip download
+      # Download pkgs from Artifactory using pip
       - name: Run pip download
         env:
             JFROG_USER: ${{ secrets.JFROG_USER }}
@@ -49,6 +51,10 @@ jobs:
             BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
             PR_NUMBER: ${{ github.event.pull_request.number || github.event.number }}
         run: |
+          set -oe pipefail
+          
+          output_file="output.txt"
+
           ./detect.sh \
             --blackduck.url=$BLACKDUCK_URL \
             --blackduck.api.token=$BLACKDUCK_API_TOKEN \
@@ -61,5 +67,31 @@ jobs:
             --detect.binary.scan.file.name.patterns="*" \
             --detect.wait.for.results=true \
             --detect.policy.check.fail.on.names="hw_bd_demo_vuln_risk" \
-            --detect.notices.report=true \
-            --detect.report.timeout=300
+            --detect.report.timeout=300 \
+            --detect.risk.report.pdf=true | tee $output_file
+
+          if [ $? -ne 0 ]; then
+            echo "One of the commands failed!!"
+          fi
+
+          echo "End of scan"
+          ls -l
+          echo "The command output is below: "
+          cat $output_file
+
+      # Post scan: Upload RiskReport.pdf to PR comments
+      - name: Upload RiskReport.pdf to PR comments
+        if: always()
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          RISK_REPORT=$(find . -name "*RiskReport.pdf" | head -n 1)
+          if [ -f "$RISK_REPORT" ]; then
+            COMMENT_BODY="""
+            ### Black Duck Risk Report
+            The scan has completed successfully. Please find the Risk Report attached.
+            """
+            gh pr comment ${{ github.event.pull_request.number || github.event.number }} --body "$COMMENT_BODY"
+          else
+            echo "RiskReport.pdf not found."
+          fi
